.MODEL SMALL
.STACK 100H
.DATA
     HELLO DB 'HELLO WORLD$'
.CODE
MAIN PROC 
     MOV AX,@DATA
     MOV DS,AX
SHOW:
     MOV AH,9
     LEA DX,HELLO
     INT 21H         ; SHOW TEXT
WAIT:         
     MOV AH,1
     INT 21H
EXIT:
     MOV AH,4CH
     INT 21H
MAIN ENDP
; CHILDREN PHOGRAM HERE
END MAIN